<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDLD9r1t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDLD9r1t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDLD9r1t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDLD9r1t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDLD9r1t\App_KernelDevDebugContainer([
    'container.build_hash' => 'DLD9r1t',
    'container.build_id' => '68107097',
    'container.build_time' => 1646778691,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDLD9r1t');
