<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOZU4hdu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOZU4hdu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOZU4hdu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOZU4hdu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOZU4hdu\App_KernelDevDebugContainer([
    'container.build_hash' => 'OZU4hdu',
    'container.build_id' => '7e18268b',
    'container.build_time' => 1649197303,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOZU4hdu');
